In [4]:
a = np.array([[1,2,3],[4,5,6]])
np.transpose(a)
a[0,1]

2

In [6]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

**1. Import numpy as np and see the version**

In [5]:
import numpy as np
print(np.__version__)

1.20.3


In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [5]:
rr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
o= np.where(rr%2==1,-1,rr)
o

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [7]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.intersect1d(a,b)

In [ ]:
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

In [7]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [12]:
arr[:, [1,0,2]]#reordering the colums using index numbers

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [14]:
print(a.argsort().argsort())
print('Array: ', a)

[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [15]:
a = np.random.randint(1,10, [5,3])

array([[9, 7, 5],
       [4, 1, 5],
       [7, 9, 2],
       [9, 5, 2],
       [4, 7, 6]])

In [16]:
# Solution 1
np.amax(a, axis=1)

# Solution 2
np.apply_along_axis(np.max, arr=a, axis=1)

array([9, 5, 9, 9, 7])